{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNPLdE/Dk+xo5eP3kVWm0lV",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/samad115/Langgraph-Agent-App/blob/main/skynav_app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "cPKhdDRlPvIS"
      },
      "outputs": [],
      "source": [
        "!pip install -q gradio"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install reportlab gradio"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RWKoRfkrXjJM",
        "outputId": "1b7f5b21-6ae0-44e1-ee2e-7d1c2aee1248"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: reportlab in /usr/local/lib/python3.12/dist-packages (5.0.0)\n",
            "Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (6.24.0)\n",
            "Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)\n",
            "Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.9)\n",
            "Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.14.2)\n",
            "Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)\n",
            "Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.141.1)\n",
            "Requirement already satisfied: gradio-client==2.6.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.6.0)\n",
            "Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)\n",
            "Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.4.1)\n",
            "Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)\n",
            "Requirement already satisfied: huggingface-hub<2.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.27.0)\n",
            "Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)\n",
            "Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)\n",
            "Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)\n",
            "Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.12.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.3)\n",
            "Requirement already satisfied: pandas<4.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.3)\n",
            "Requirement already satisfied: pydantic<=3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.13.4)\n",
            "Requirement already satisfied: pydub<1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)\n",
            "Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.32)\n",
            "Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (2025.2)\n",
            "Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)\n",
            "Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)\n",
            "Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)\n",
            "Requirement already satisfied: starlette<2.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.6.0)\n",
            "Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.14.0)\n",
            "Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.27.1)\n",
            "Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.16.0)\n",
            "Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.3)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==2.6.0->gradio) (2025.3.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.18)\n",
            "Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.4)\n",
            "Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.5)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.7.22)\n",
            "Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)\n",
            "Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)\n",
            "Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (8.4.2)\n",
            "Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (3.32.3)\n",
            "Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (1.6.0)\n",
            "Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (4.67.3)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=1.0->gradio) (2026.3)\n",
            "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (0.8.0)\n",
            "Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (2.46.4)\n",
            "Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)\n",
            "Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install --upgrade gradio"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ricWhpMiv0XZ",
        "outputId": "e24f7428-595f-4170-cab2-fba51dcdf71a"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (6.24.0)\n",
            "Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.14.2)\n",
            "Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)\n",
            "Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.141.1)\n",
            "Requirement already satisfied: gradio-client==2.6.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.6.0)\n",
            "Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)\n",
            "Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.4.1)\n",
            "Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)\n",
            "Requirement already satisfied: huggingface-hub<2.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.27.0)\n",
            "Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)\n",
            "Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)\n",
            "Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)\n",
            "Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.12.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.3)\n",
            "Requirement already satisfied: pandas<4.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.3)\n",
            "Requirement already satisfied: pillow<13.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)\n",
            "Requirement already satisfied: pydantic<=3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.13.4)\n",
            "Requirement already satisfied: pydub<1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)\n",
            "Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.32)\n",
            "Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (2025.2)\n",
            "Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)\n",
            "Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)\n",
            "Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)\n",
            "Requirement already satisfied: starlette<2.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.6.0)\n",
            "Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.14.0)\n",
            "Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.27.1)\n",
            "Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.16.0)\n",
            "Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.3)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==2.6.0->gradio) (2025.3.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.18)\n",
            "Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.4)\n",
            "Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.5)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.7.22)\n",
            "Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)\n",
            "Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)\n",
            "Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (8.4.2)\n",
            "Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (3.32.3)\n",
            "Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (1.6.0)\n",
            "Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.16.0->gradio) (4.67.3)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=1.0->gradio) (2026.3)\n",
            "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (0.8.0)\n",
            "Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (2.46.4)\n",
            "Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)\n",
            "Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import gradio as gr\n",
        "import random\n",
        "import re\n",
        "import smtplib\n",
        "import os\n",
        "import urllib.request\n",
        "from email.mime.text import MIMEText\n",
        "from email.mime.multipart import MIMEMultipart\n",
        "from email.mime.application import MIMEApplication\n",
        "\n",
        "from reportlab.lib.pagesizes import letter\n",
        "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle\n",
        "from reportlab.lib import colors\n",
        "from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle\n",
        "\n",
        "# =========================================================\n",
        "# 1. GMAIL CONFIGURATION\n",
        "# =========================================================\n",
        "SENDER_EMAIL = \"mohammedsamad475@gmail.com\"        # 👈 Enter your Gmail address\n",
        "SENDER_PASSWORD = \"eqqz srwy qhzl qhas\"       # 👈 Enter your 16-digit Gmail App Password\n",
        "\n",
        "# =========================================================\n",
        "# 2. PDF GENERATOR & EMAIL DISPATCH ENGINES\n",
        "# =========================================================\n",
        "def generate_pdf_ticket(pnr, passenger_name, email, flight_info, seat_info, total_price, refund_policy):\n",
        "    try:\n",
        "        filename = f\"Ticket_{pnr}.pdf\"\n",
        "        doc = SimpleDocTemplate(filename, pagesize=letter)\n",
        "        styles = getSampleStyleSheet()\n",
        "        story = []\n",
        "\n",
        "        title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, textColor=colors.HexColor(\"#0284c7\"))\n",
        "        story.append(Paragraph(\"✈️ SkyNav Global Aviation - Official E-Ticket\", title_style))\n",
        "        story.append(Spacer(1, 10))\n",
        "\n",
        "        data = [\n",
        "            [\"PNR / Ticket ID:\", pnr],\n",
        "            [\"Passenger Name:\", passenger_name],\n",
        "            [\"Passenger Email:\", email],\n",
        "            [\"Flight Route & Details:\", flight_info],\n",
        "            [\"Assigned Seat:\", seat_info],\n",
        "            [\"Total Amount Paid:\", f\"INR {total_price:,}\"],\n",
        "            [\"Refund Policy:\", refund_policy],\n",
        "            [\"Booking Status:\", \"CONFIRMED & ISSUED ✅\"]\n",
        "        ]\n",
        "\n",
        "        t = Table(data, colWidths=[140, 320])\n",
        "        t.setStyle(TableStyle([\n",
        "            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor(\"#f0f9ff\")),\n",
        "            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor(\"#1e293b\")),\n",
        "            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),\n",
        "            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor(\"#cbd5e1\")),\n",
        "            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),\n",
        "            ('TOPPADDING', (0, 0), (-1, -1), 6),\n",
        "        ]))\n",
        "\n",
        "        story.append(t)\n",
        "        doc.build(story)\n",
        "        return filename\n",
        "    except Exception as e:\n",
        "        print(f\"PDF Error: {e}\")\n",
        "        return None\n",
        "\n",
        "def send_real_email(to_email, subject, body_text, pdf_path=None):\n",
        "    clean_pwd = SENDER_PASSWORD.replace(\" \", \"\")\n",
        "    if \"xxxx\" in clean_pwd or len(clean_pwd) == 0:\n",
        "        return f\"⚠️ [SMTP NOTICE]: Gmail App Password missing. Email simulated for '{to_email}'.\"\n",
        "\n",
        "    try:\n",
        "        msg = MIMEMultipart()\n",
        "        msg[\"Subject\"] = subject\n",
        "        msg[\"From\"] = f\"SkyNav AI Assistant <{SENDER_EMAIL}>\"\n",
        "        msg[\"To\"] = to_email\n",
        "        msg.attach(MIMEText(body_text, \"plain\"))\n",
        "\n",
        "        if pdf_path and os.path.exists(pdf_path):\n",
        "            with open(pdf_path, \"rb\") as f:\n",
        "                part = MIMEApplication(f.read(), _subtype=\"pdf\")\n",
        "                part.add_header('Content-Disposition', 'attachment', filename=os.path.basename(pdf_path))\n",
        "                msg.attach(part)\n",
        "\n",
        "        server = smtplib.SMTP(\"smtp.gmail.com\", 587, timeout=10)\n",
        "        server.starttls()\n",
        "        server.login(SENDER_EMAIL, clean_pwd)\n",
        "        server.sendmail(SENDER_EMAIL, to_email, msg.as_string())\n",
        "        server.quit()\n",
        "        return f\"📧 [REAL EMAIL SENT]: Successfully delivered to '{to_email}'!\"\n",
        "    except Exception as e:\n",
        "        return f\"❌ Email Error: {str(e)}\"\n",
        "\n",
        "# =========================================================\n",
        "# 3. BACKEND FLIGHT DATA & SESSION STATE\n",
        "# =========================================================\n",
        "CITIES_MAP = {\n",
        "    \"delhi\": \"Delhi (DEL)\", \"london\": \"London (LHR)\",\n",
        "    \"dubai\": \"Dubai (DXB)\", \"mumbai\": \"Mumbai (BOM)\",\n",
        "    \"bengaluru\": \"Bengaluru (BLR)\", \"new york\": \"New York (JFK)\"\n",
        "}\n",
        "\n",
        "agent_session_data = {\n",
        "    \"source\": \"Dubai (DXB)\",\n",
        "    \"dest\": \"Delhi (DEL)\",\n",
        "    \"date\": \"2026-09-12\",\n",
        "    \"passenger\": \"Samad\",\n",
        "    \"email\": \"imission418@gmail.com\",\n",
        "    \"selected_flight\": None,\n",
        "    \"selected_seat\": None,\n",
        "    \"step\": \"SEARCH\",\n",
        "    \"otp\": None,\n",
        "    \"pnr\": None,\n",
        "    \"price\": 45000\n",
        "}\n",
        "\n",
        "def get_flight_options(source, dest, date_str):\n",
        "    return (\n",
        "        f\"✈️ **SkyNav Search Results ({source} ➔ {dest}) | Date: {date_str}**\\n\\n\"\n",
        "        f\"1️⃣ **Air India (AI-502)** | Dep: 08:00 AM | Price: ₹42,000\\n\"\n",
        "        f\"2️⃣ **Emirates (EK-513)** | Dep: 02:30 PM | Price: ₹48,000\\n\"\n",
        "        f\"3️⃣ **IndiGo (6E-95)** | Dep: 10:15 PM | Price: ₹38,000\\n\"\n",
        "    )\n",
        "\n",
        "# =========================================================\n",
        "# 4. CHAT RESPONSE FUNCTION (STATE WORKFLOW ENGINE)\n",
        "# =========================================================\n",
        "def ai_agent_response(message, history):\n",
        "    global agent_session_data\n",
        "    msg_lower = message.lower().strip()\n",
        "    words = re.findall(r'\\b\\w+\\b', msg_lower)\n",
        "\n",
        "    # Extract Cities & Dates dynamically\n",
        "    found_cities = [city_full for city_key, city_full in CITIES_MAP.items() if city_key in msg_lower]\n",
        "    date_match = re.search(r'\\d{2,4}[-/]\\d{1,2}[-/]\\d{2,4}', message)\n",
        "    if date_match:\n",
        "        agent_session_data[\"date\"] = date_match.group(0)\n",
        "\n",
        "    # STEP 1: Verify OTP (Final Step)\n",
        "    if re.match(r'^\\d{6}$', message.strip()):\n",
        "        input_otp = message.strip()\n",
        "        if agent_session_data[\"otp\"] and input_otp == agent_session_data[\"otp\"]:\n",
        "            pdf_file = generate_pdf_ticket(\n",
        "                pnr=agent_session_data[\"pnr\"],\n",
        "                passenger_name=agent_session_data[\"passenger\"],\n",
        "                email=agent_session_data[\"email\"],\n",
        "                flight_info=f\"{agent_session_data['source']} ➔ {agent_session_data['dest']} | Date: {agent_session_data['date']}\",\n",
        "                seat_info=agent_session_data[\"selected_seat\"],\n",
        "                total_price=agent_session_data[\"price\"],\n",
        "                refund_policy=\"Standard Non-Refundable Premium\"\n",
        "            )\n",
        "\n",
        "            ticket_res = send_real_email(\n",
        "                to_email=agent_session_data[\"email\"],\n",
        "                subject=f\"✈️ E-Ticket Confirmation - PNR: {agent_session_data['pnr']}\",\n",
        "                body_text=\"Your payment is successful! Your official PDF E-Ticket is attached.\",\n",
        "                pdf_path=pdf_file\n",
        "            )\n",
        "\n",
        "            agent_session_data[\"step\"] = \"COMPLETED\"\n",
        "            return (\n",
        "                f\"🎉 **PAYMENT SUCCESSFUL & TICKET ISSUED!**\\n\\n\"\n",
        "                f\"✅ **PNR:** {agent_session_data['pnr']}\\n\"\n",
        "                f\"🪑 **Seat Assigned:** {agent_session_data['selected_seat']}\\n\"\n",
        "                f\"📄 **PDF Generated:** `{pdf_file}`\\n\"\n",
        "                f\"📧 **Status:** {ticket_res}\\n\\n\"\n",
        "                f\"Your official PDF E-Ticket has been delivered to your email. Safe travels!\"\n",
        "            )\n",
        "        else:\n",
        "            return \"❌ Invalid OTP! Please enter the correct 6-digit code sent to your email.\"\n",
        "\n",
        "    # STEP 2: Handle Seat Choice after Flight Selection\n",
        "    elif agent_session_data[\"step\"] == \"SEAT_SELECTION\":\n",
        "        agent_session_data[\"selected_seat\"] = message.strip().upper()\n",
        "        agent_session_data[\"otp\"] = str(random.randint(100000, 999999))\n",
        "        agent_session_data[\"pnr\"] = f\"SKYN-{random.randint(1000, 9999)}\"\n",
        "        agent_session_data[\"step\"] = \"OTP\"\n",
        "\n",
        "        email_res = send_real_email(\n",
        "            to_email=agent_session_data[\"email\"],\n",
        "            subject=f\"🔑 SkyNav Payment OTP: {agent_session_data['otp']}\",\n",
        "            body_text=f\"Your SkyNav Payment Authorization OTP for {agent_session_data['selected_flight']} (Seat {agent_session_data['selected_seat']}) is: {agent_session_data['otp']}\"\n",
        "        )\n",
        "\n",
        "        return (\n",
        "            f\"✅ **Seat {agent_session_data['selected_seat']} Confirmed!**\\n\\n\"\n",
        "            f\"✈️ **Flight:** {agent_session_data['selected_flight']}\\n\"\n",
        "            f\"📋 **Booking PNR:** {agent_session_data['pnr']}\\n\"\n",
        "            f\"💰 **Total Amount:** ₹{agent_session_data['price']:,}\\n\\n\"\n",
        "            f\"🔒 A 6-digit security OTP has been sent to `{agent_session_data['email']}`.\\n\"\n",
        "            f\"({email_res})\\n\\n\"\n",
        "            f\"Please enter the **6-digit OTP** here to authorize payment.\"\n",
        "        )\n",
        "\n",
        "   # STEP 3: Handle Flight Choice (Presents Real Airplane Seat Map)\n",
        "    elif any(k in words for k in [\"1\", \"2\", \"3\", \"emirates\", \"indigo\"]) or \"air india\" in msg_lower:\n",
        "        if \"2\" in words or \"emirates\" in words:\n",
        "            agent_session_data[\"selected_flight\"] = \"Emirates (EK-513)\"\n",
        "            agent_session_data[\"price\"] = 48000\n",
        "        elif \"3\" in words or \"indigo\" in words:\n",
        "            agent_session_data[\"selected_flight\"] = \"IndiGo (6E-95)\"\n",
        "            agent_session_data[\"price\"] = 38000\n",
        "        else:\n",
        "            agent_session_data[\"selected_flight\"] = \"Air India (AI-502)\"\n",
        "            agent_session_data[\"price\"] = 42000\n",
        "\n",
        "        agent_session_data[\"step\"] = \"SEAT_SELECTION\"\n",
        "\n",
        "        # Direct link to a clear aircraft cabin seating layout\n",
        "        airplane_seat_map_url = \"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Seat_map_A320.svg/800px-Seat_map_A320.svg.png\"\n",
        "\n",
        "        return (\n",
        "            f\"🎯 **Selected Flight:** {agent_session_data['selected_flight']}\\n\\n\"\n",
        "            f\"✈️ **AIRCRAFT CABIN SEAT MAP**\\n\\n\"\n",
        "            f\"![Aircraft Seat Map]({airplane_seat_map_url})\\n\\n\"\n",
        "            f\"📍 **Seat Location & Availability Guide:**\\n\"\n",
        "            f\"* 👑 **Business Class (Front Section - Rows 1-5):**\\n\"\n",
        "            f\"  * `1A` ➔ Front Left Window\\n\"\n",
        "            f\"  * `1C` ➔ Front Left Aisle\\n\"\n",
        "            f\"  * `2D` ➔ Front Right Aisle\\n\"\n",
        "            f\"* 🚀 **Extra Legroom Seats (Exit Rows 11-12):**\\n\"\n",
        "            f\"  * `11A` ➔ Exit Row Left Window\\n\"\n",
        "            f\"  * `11C` ➔ Exit Row Left Aisle\\n\"\n",
        "            f\"  * `12F` ➔ Exit Row Right Window\\n\"\n",
        "            f\"* 💺 **Standard Economy (Rows 14-38):**\\n\"\n",
        "            f\"  * `14A` ➔ Economy Window\\n\"\n",
        "            f\"  * `15B` ➔ Economy Middle\\n\"\n",
        "            f\"  * `25C` ➔ Economy Aisle\\n\\n\"\n",
        "            f\"👉 **How to Book:** Simply type your desired seat code (e.g., `11C` or `1A`) into the chat box below to select it!\"\n",
        "        )\n",
        "    # STEP 4: Initial Search Request\n",
        "    elif len(found_cities) >= 2 or any(k in words for k in [\"book\", \"fly\", \"flight\"]):\n",
        "        if len(found_cities) >= 2:\n",
        "            agent_session_data[\"source\"] = found_cities[0]\n",
        "            agent_session_data[\"dest\"] = found_cities[1]\n",
        "\n",
        "        flights = get_flight_options(agent_session_data[\"source\"], agent_session_data[\"dest\"], agent_session_data[\"date\"])\n",
        "        return (\n",
        "            f\"Understood! Here are the extracted booking details:\\n\\n\"\n",
        "            f\"🔍 **AI Agent Log:** Source: `{agent_session_data['source']}`, Destination: `{agent_session_data['dest']}`, Date: `{agent_session_data['date']}`\\n\\n\"\n",
        "            f\"Available Flight Options:\\n\\n{flights}\\n\"\n",
        "            f\"Reply with **1** (Air India), **2** (Emirates), or **3** (IndiGo) to select your flight!\"\n",
        "        )\n",
        "\n",
        "    # STEP 5: Standalone Greetings\n",
        "    elif any(greeting in words for greeting in [\"hello\", \"hi\", \"hey\"]):\n",
        "        return \"Hello! I am your SkyNav AI Travel Agent. Where would you like to travel?\"\n",
        "\n",
        "    else:\n",
        "        return \"I can assist you! Reply with **1**, **2**, or **3** to pick a flight, or enter a request like: *'I want to book a flight from Dubai to Delhi 2026-09-12'*.\"\n",
        "\n",
        "# =========================================================\n",
        "# 5. GRADIO UI LAUNCHER\n",
        "# =========================================================\n",
        "demo = gr.ChatInterface(\n",
        "    fn=ai_agent_response,\n",
        "    title=\"✈️ SkyNav AI: Autonomous Travel Agent\",\n",
        "    description=\"Command the AI agent in natural English (e.g., `I want to book a flight from Dubai to Delhi 2026-09-12`)\"\n",
        ")\n",
        "\n",
        "demo.launch(share=True)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 611
        },
        "id": "z2kfcLxc2cr7",
        "outputId": "36d0ad30-88eb-4f67-b68b-83881ff0e40b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Colab notebook detected. To show errors in colab notebook, set debug=True in launch()\n",
            "* Running on public URL: https://a4934462b83eda48e1.gradio.live\n",
            "\n",
            "This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "<div><iframe src=\"https://a4934462b83eda48e1.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": []
          },
          "metadata": {},
          "execution_count": 18
        }
      ]
    }
  ]
}